<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Framework\Data\Helper\PostHelper;
use Magento\Framework\View\Element\Template;
use Opengento\CountryStoreSwitcher\ViewModel\Localized;
use Opengento\CountryStoreSwitcher\ViewModel\SwitchCountry\Forehead;
use Opengento\CountryStoreSwitcher\ViewModel\SwitcherUrlProvider;

/** @var Template $block */

$helper = $this->helper(PostHelper::class);

/** @var Localized $localized */
$localized = $block->getData('localized');

/** @var SwitcherUrlProvider $switcherProvider */
$switcherProvider = $block->getData('switcherProvider');

/** @var Forehead $countryViewModel */
$countryViewModel = $block->getData('countryViewModel');

$countries = $countryViewModel->getCountries();
?>
<?php if (count($countries)): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher country country-store-switcher" data-ui-id="country-store-switcher" id="country-store-switcher<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Select Country')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="country-store-switcher-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong data-bind="scope: 'countryStoreData'" >
                    <span data-bind="text: countryStoreData().name">
                        <?= $block->escapeHtml(__('Select Country')) ?>
                    </span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown" data-target="dropdown" data-bind="scope: 'countryStoreData'" >
                <?php foreach ($countries as $country): ?>
                    <li class="view-<?= $block->escapeHtmlAttr(strtolower($country->getCode())) ?> switcher-option"
                        data-bind="visible: countryStoreData().code !== '<?= $block->escapeHtml($country->getCode()) ?>'">
                        <a href="#" data-post='<?= $helper->getPostData($block->getData('urlAction'), $switcherProvider->getTargetParams($country)) ?>'>
                            <?= $block->escapeHtml($localized->getCountryName($country)) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <?= $block->getChildHtml('more') ?>
        </div>
    </div>
<?php endif; ?>
